services:
  - type: web
    name: takymed
    env: docker
    region: frankfurt # ou une autre région selon votre choix
    plan: starter # Requis pour utiliser un disque persistant
    dockerfilePath: ./Dockerfile
    disk:
      name: takymed-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_PATH
        value: /app/data/bd.sqlite
